---
title: "analysis"
author: "Yuka Chen"
date: "11/8/2021"
output: html_document
---
```{r}
library(tidyverse)
library(ggrepel)
```

```{r}
Africa2 <- read_csv("~/STAT_GROUPPROJECT_COVID19/Africa2.csv")
world_covid <- read_csv("~/STAT_GROUPPROJECT_COVID19/world_covid.csv")
```



```{r}
Africa2 %>% 
  dplyr::select(total_deaths_per_million, gdp_per_capita, female_smokers, male_smokers, location) %>%
  drop_na() %>%  
  group_by(location, gdp_per_capita, total_deaths_per_million) %>% 
  ggplot(aes(log(gdp_per_capita),log(total_deaths_per_million), color = location))+
  geom_point(na.rm = TRUE)+
  geom_smooth(method = lm, se = FALSE)
```

```{r}
ggplot(Africa2,
       aes(x = log(gdp_per_capita), 
           y = log(total_deaths_per_million))) +
  geom_bar(stat = "identity")
```

```{r}
Africa2 %>% 
  dplyr::select(total_deaths_per_million, gdp_per_capita, female_smokers, male_smokers, location) %>%
  group_by(location, gdp_per_capita, total_deaths_per_million) %>% 
  drop_na() %>%  
  ggplot(aes(log(gdp_per_capita),log(total_deaths_per_million), color = location))+
  geom_point(na.rm = TRUE)+
  geom_smooth(method = lm, se = FALSE) 
```

```{r}
world_covid %>%
  arrange(desc(gdp_per_capita)) %>% 
  filter(date == "2021-04-24") %>%  
  dplyr::select(location,
         continent,
         total_deaths_per_million, 
         total_vaccinations, 
         people_fully_vaccinated, 
         people_vaccinated, 
         total_tests_per_thousand, 
         gdp_per_capita, 
         extreme_poverty,
         male_smokers,
         female_smokers,
         population, 
         population_density,
         stringency_index,
         diabetes_prevalence) %>% 
  drop_na() %>% 
  mutate(smoker_total = male_smokers + female_smokers) %>% 
  relocate(smoker_total, .before = male_smokers)-> covid_world123
  

head(covid_world123, n=15) -> high_gdp_15
tail(covid_world123, n=15) -> low_gdp_15

ls(high_gdp_15)
ls(low_gdp_15)

sample_n(covid_world123, 30) -> stats614_project_30samples_covid


```

```{r}
world_covid %>%
  dplyr::select(date,
         location,
         continent,
         total_deaths_per_million, 
         total_vaccinations, 
         people_fully_vaccinated, 
         people_vaccinated, 
         total_tests_per_thousand, 
         gdp_per_capita, 
         extreme_poverty,
         male_smokers,
         female_smokers,
         population, 
         population_density,
         stringency_index,
         diabetes_prevalence) %>% 
  drop_na() %>% 
  mutate(smoker_total = male_smokers + female_smokers) %>% 
  relocate(smoker_total, .before = male_smokers)-> covid_world1234
```
```{r}
  covid_world1234 %>% 
  group_by(location, continent, population_density, stringency_index, diabetes_prevalence, smoker_total,male_smokers,female_smokers) -> world_covid12345
```

```{r}
mydata <- world_covid %>% 
  filter(location == "Paraguay" | location =="Kazakhstan"| location == "Austria"| location =="Croatia"| location =="Ecuador"| location =="Bulgaria"|  location =="Ireland"| location =="Norway"| location =="United States"|  location =="Italy"| location =="Uruguay"| location =="Israel"| location =="Ukraine"| location =="Canada"| location =="Lithuania"|  location =="Denmark"| location =="Portugal"| location =="Chile"| location =="Colombia"| location =="Argentina"| location =="Latvia"| location =="Panama"| location =="Mexico"| location =="Malta"| location =="Slovakia"| location =="Malaysia"| location =="Russia"| location =="Estonia"| location =="United Kingdom"| location =="Turkey") %>% 
  dplyr::select(
         date,
         location,
         continent,
         total_deaths_per_million, 
         new_deaths,
         total_vaccinations, 
         people_fully_vaccinated, 
         people_vaccinated, 
         total_tests_per_thousand, 
         gdp_per_capita, 
         extreme_poverty,
         male_smokers,
         female_smokers,
         population, 
         population_density,
         stringency_index,
         diabetes_prevalence) %>% 
  drop_na() %>% 
  mutate(smoker_total = male_smokers + female_smokers) %>% 
  relocate(smoker_total, .before = male_smokers)

mydata

```


```{r}
mydata %>% 
  drop_na() %>% 
  ggplot(aes(log(people_fully_vaccinated),log(new_deaths)))+
  geom_jitter(na.rm = TRUE)+
  geom_smooth(method = lm, se = FALSE)+
  facet_wrap(~location)+
  ylab("Death Numbers")+
  xlab("People Fully Vaccinated")
```
```{r}
world_covid %>%
  arrange(gdp_per_capita) %>% 
  filter(date == "2021-04-24"|location == "Paraguay" | location =="Kazakhstan"| location == "Austria"| location =="Croatia"| location =="Ecuador"| location =="Bulgaria"|  location =="Ireland"| location =="Norway"| location =="United States"|  location =="Italy"| location =="Uruguay"| location =="Israel"| location =="Ukraine"| location =="Canada"| location =="Lithuania"|  location =="Denmark"| location =="Portugal"| location =="Chile"| location =="Colombia"| location =="Argentina"| location =="Latvia"| location =="Panama"| location =="Mexico"| location =="Malta"| location =="Slovakia"| location =="Malaysia"| location =="Russia"| location =="Estonia"| location =="United Kingdom"| location =="Turkey") %>%  
  dplyr::select(
    date, 
    location,
         continent,
         total_deaths_per_million,
         new_deaths,
         total_vaccinations, 
         people_fully_vaccinated, 
         people_vaccinated, 
         total_tests_per_thousand, 
         gdp_per_capita, 
         extreme_poverty,
         male_smokers,
         female_smokers,
         population, 
         population_density,
         stringency_index,
         diabetes_prevalence) %>% 
  drop_na() %>% 
  mutate(smoker_total = male_smokers + female_smokers) %>% 
  relocate(smoker_total, .before = male_smokers)-> mydata2 ##has date

write.csv(mydata2, file = "thirty_countries_covid_.csv")
```

```{r}
mydata2 %>% 
  filter(date == "2021-04-24") -> mydata3 ## on date == "2021-04-24"
```


```{r}
world_covid %>% 
  filter(date == "2021-02-20") -> whole_world_april_24 ## on date == "2021-04-24"
```

```{r}

mydata2 %>% 
  dplyr::select(total_deaths_per_million,gdp_per_capita, location) %>% 
  ggplot(aes(x = gdp_per_capita, 
           fill = location)) +
  geom_density(alpha = 0.4) +
  labs(title = "xxx")+
  xlab("GDP per Capita")+
  ylab("Death")
```

```{r}
mydata2 %>% 
  dplyr::select(new_deaths,gdp_per_capita, location) %>% 
  ggplot(aes(x = log(gdp_per_capita), 
             y = log(new_deaths),
             color = location)) +
  geom_jitter(stat = "identity")+
  geom_text(aes(label= ifelse(log(gdp_per_capita) < 8.5,
     as.character(location),'')),hjust=0,vjust=0)+
  labs(title = "Death Numbers by COVID19 vs GDP per Capita")+
  xlab("GDP per Capita")+
  ylab("Death") -> mydata2_outlier
 mydata2_outlier
```

```{r}
mydata3 %>% 
  ggplot(aes(x = gdp_per_capita, y = total_deaths_per_million))+
  geom_point()+
  geom_label_repel(aes(label = location))+
  labs(title = "Death Numbers by COVID19 vs GDP per Capita")+
  xlab("GDP per Capita")+
  ylab("Death")
```
```{r}
library(MASS)
lm(total_deaths_per_million ~ smoker_total, data = mydata) -> j
summary(j)
```

```{r}


mydata3 %>% 
  ggplot(aes(x = smoker_total, y = total_deaths_per_million))+
  geom_point()+
  geom_label_repel(aes(label = location))+
  geom_smooth( se = FALSE)+
  labs(title = "Death Numbers by COVID19 vs GDP per Capita")+
  xlab("smoker")+
  ylab("Death")
```
```{r}
lm(total_deaths_per_million ~ female_smokers, data = mydata) ->k
summary(k)

lm(total_deaths_per_million ~ male_smokers, data = mydata) ->l
summary(l)
```

```{r}
mydata3 %>% 
  ggplot(aes(x =female_smokers, y = total_deaths_per_million))+
  geom_point()+
  geom_text_repel(aes(label = location))+
  geom_smooth( se = FALSE)+
  labs(title = "Death Numbers by COVID19 vs GDP per Capita")+
  xlab("Female smoker")+
  ylab("Death")

mydata3 %>% 
  ggplot(aes(x = male_smokers, y = total_deaths_per_million))+
  geom_point()+
  geom_text_repel(aes(label = location))+
  geom_smooth( se = FALSE)+
  labs(title = "Death Numbers by COVID19 vs GDP per Capita")+
  xlab("Male smoker")+
  ylab("Death")
```
```{r}
lm(total_deaths_per_million ~ extreme_poverty, data = mydata) -> p
summary(p)
```


```{r}
mydata3 %>% 
  ggplot(aes(x = extreme_poverty, y = total_deaths_per_million))+
  geom_point()+
  geom_text_repel(aes(label = location))+
  geom_smooth( se = FALSE)+
  labs(title = "Death Numbers by COVID19 vs GDP per Capita")+
  xlab("Extreme Poverty Rate")+
  ylab("Death")

mydata%>% 
  ggplot(aes(x = extreme_poverty, y = total_deaths_per_million))+
  geom_point()+
  geom_text_repel(aes(label = location))+
  geom_smooth( se = FALSE)+
  labs(title = "Death Numbers by COVID19 vs GDP per Capita")+
  xlab("Extreme Poverty Rate")+
  ylab("Death")
```
```{r}
mydata3 %>% 
  ggplot(aes(x = population, y = total_deaths_per_million))+
  geom_point()+
  geom_text_repel(aes(label = location))+
  geom_smooth( se = FALSE)+
  labs(title = "Death Numbers by COVID19 vs GDP per Capita")+
  xlab("Extreme Poverty Rate")+
  ylab("Death")

```

```{r}

## maybe pick another date that all continents have all info
whole_world_april_24 %>% 
  group_by(date) %>% 
  filter(continent == "Asia") %>% 
  ggplot(aes(log(total_tests_per_thousand), log(new_deaths)))+
  geom_smooth(method= lm, se = FALSE)+
  geom_jitter()+
  labs(title = "COVID Death vs test numbers in asia ")+
  xlab("total tests per thousand")+
  ylab("Death")
  

whole_world_april_24 %>% 
  group_by(date) %>% 
  filter(continent == "Africa") %>% 
  ggplot(aes(log(total_tests_per_thousand), log(new_deaths)))+
  geom_smooth(method= lm, se = FALSE)+
  geom_jitter()+
  labs(title = "COVID Death vs test numbers in Africa ")+
  xlab("total tests per thousand")+
  ylab("Death")

whole_world_april_24 %>% 
  group_by(date) %>% 
  filter(continent == "Europe") %>% 
  ggplot(aes(log(total_tests_per_thousand), log(new_deaths)))+
  geom_smooth(method= lm, se = FALSE)+
  geom_jitter()+
  labs(title = "COVID Death vs test numbers in Europe ")+
  xlab("total tests per thousand")+
  ylab("Death")

whole_world_april_24 %>% 
  group_by(date) %>% 
  filter(continent == "Oceania") %>% 
  ggplot(aes(log(total_tests_per_thousand), log(new_deaths)))+
  geom_smooth(method= lm, se = FALSE)+
  geom_jitter()+
  labs(title = "COVID Death vs test numbers in Oceania ")+
  xlab("total tests per thousand")+
  ylab("Death")


whole_world_april_24 %>% 
  group_by(date) %>% 
  filter(continent == "NorthAmerica") %>% 
  ggplot(aes(log(total_tests_per_thousand), log(new_deaths)))+
  geom_smooth(method= lm, se = FALSE)+
  geom_jitter()+
  labs(title = "COVID Death vs test numbers in NorthAmerica ")+
  xlab("total tests per thousand")+
  ylab("Death")

whole_world_april_24 %>% 
  group_by(date) %>% 
  filter(continent == "SouthAmerica") %>% 
  ggplot(aes(log(total_tests_per_thousand), log(new_deaths)))+
  geom_smooth(method= lm, se = FALSE)+
  geom_jitter()+
  labs(title = "COVID Death vs test numbers in SouthAmerica ")+
  xlab("total tests per thousand")+
  ylab("Death")


a
```

